#!/usr/bin/perl
use Term::ReadKey;

print "Username: ";
$username = ReadLine 0;

print "Enter your password: ";
ReadMode 'noecho';
$password = ReadLine 0;
ReadMode 'normal';

print "\n";

print "Server URL: ";
$username = ReadLine 0;

print "\n";

chomp $server;
chomp $username;
chomp $password;

print "Thanks unfortunately nothing more is implemented\n";
