#!/usr/bin/perl
use Term::ReadKey;
use Getopt::Long;
use Frontier::Client;

$version_number = "0.1.3";
$version_name = "Thales";

#Commandline options
$list_servers = '';
$help = '';
$version = '';
$list_inactive_servers = '';

#User input
$username = '';
$password = '';
$server_url = '';

$coder = Frontier::RPC2->new;

GetOptions (
		'list-servers' => \$list_servers,
		'help' => \$help, 'h' => \$help,
		'u=s' => \$username, 'username=s' => \$username,
		'v' => \$version, 'version' => \$version,
		'url=s' => \$server_url,
		'list-inactive-servers' => \$list_inactive_servers,
);

if ( $help ) {

	print "Usage: spwlk_cli [options]\n\n";
	print "OPTIONS\n\n";
	print "\t-h --help\tshow this help message\n";
	print "\t-v --version\tshow version info\n\n";
	print "\t-u --username [username]\n";
	print "\t--url [Spacewalk server URL]\n\n";
	print "\t--list-servers\tlist all servers the user have access to\n";
	print "\t--list-inactive-servers\tlist all inactive servers the user have access to\n";
	
	print "\n";

} elsif ( $version ) {

	print "spwlk_cli v" . $version_number . " " . $version_name . "\n";
	print "(C) 2015 Lars Dennis Renneberg Andersen\n";
	print "\@-Boy Software - http://software.at-boy.net/\n"

} else {

	if ( $username eq "" ) {

		print "Username: ";
		$username = ReadLine 0;

	} else {

		print "Username: " . $username . "\n";

	}

        if ( $server_url eq "" ) {

                print "Server URL: ";
                $server_url = ReadLine 0;

        } else {

                print "Server URL: " . $server_url . "\n";

        }

	print "Enter your password: ";
	ReadMode 'noecho';
	$password = ReadLine 0;
	ReadMode 'normal';

	print "\n";

	chomp $server_url;
	chomp $username;
	chomp $password;

	$client = new Frontier::Client(url => "http://". $server_url. "/rpc/api");
        $session = $client->call('auth.login',$username, $password);

        if ( $list_servers || $list_inactive_servers ) {

		if ( $list_inactive_servers ) {
			$systems = $client->call('system.listInactiveSystems', $session);
		} else {

                	$systems = $client->call('system.listSystems', $session);

		}

	        foreach my $system ( @$systems ) {

        		$date_time = $system->{'last_checkin'};
                	$date_time_str = sprintf("%d-%02d-%02d %02d:%02d", unpack('A4A2A2xA2xA2xA2', $date_time->value()));

	                print "ID: " . $system->{'id'} . " HOST: " . $system->{'name'} . " LastCheckedIn: " . $date_time_str . "\n";

                }

        } else {

                print "You should try --list-all-servers it is the only feature implemented at the moment\n";

        }

        $client->call('auth.logout', $session);
}
